### ISSUE TITLE
ACTIVIDAD 2 VALIDACION DE DOCUMENTOS

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-judith#4]
[VALIDACION DE LOS CASOS DE USO_JudithReynaCruzSantiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-judith/files/10836008/VALIDACION.DE.LOS.CASOS.DE.USO_JudithReynaCruzSantiago.pdf)

**Comment by Brenda-hub2** [comment]
equipo conectando:
buen trabajo 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
